// Automatically generated by MockGen. DO NOT EDIT!
// Source: internal/repository/repository.go

package mocks

import (
    // "url-shortener/pkg/storage"

    "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage interface
type MockStorage struct {
    mock.Mock
}

// GetLongUrl provides a mock function with given fields: ctx, shortUrl
func (_m *MockStorage) GetLongUrl(shortUrl string) (string, error) {
    ret := _m.Called(shortUrl)

    var r0 string
    if rf, ok := ret.Get(0).(func( string) string); ok {
        r0 = rf( shortUrl)
    } else {
        r0 = ret.Get(0).(string)
    }

    var r1 error
    if rf, ok := ret.Get(1).(func( string) error); ok {
        r1 = rf( shortUrl)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// Insert provides a mock function with given fields: ctx, shortURL, longURL
func (_m *MockStorage) Insert(shortURL, longURL string) error {
    ret := _m.Called(shortURL, longURL)

    var r0 error
    if rf, ok := ret.Get(0).(func( string, string) error); ok {
        r0 = rf(shortURL, longURL)
    } else {
        r0 = ret.Error(0)
    }

    return r0
}
