version: '3'

networks:
  my_network:
    driver: bridge

services:
  user-service:
    build:
      context: .
      dockerfile: dockerfile.server
    restart: always
    volumes:
      - ./logs:/app/logs:z
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -c 'max_connections=250'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
          ]
      interval: 5s
      retries: 3
    networks:
      - my_network

  migrate:
    build:
      context: .
      dockerfile: dockerfile.migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - my_network
